### ISSUE TITLE
[3] Venue Selection

### ISSUE THREAD

**Issue by sigdelsanjog** [Kathmandu-University-Computer-Club/SFD2017#1]
#3 Feasible Solution for us would be either IT PARK or KU.

**Comment by shubham4564** [comment]
Getting IT park will be hard, I guess. Also there are very limited resources to use, tables and chairs. what are the basic resources we will be needing will depend on where to choose the venue i guess..

**Comment by sigdelsanjog** [comment]
@shubham4564 Those are valid reasons. I think we should stick with Venue as KU Premises.
Lets finalize this before 3rd September,2017.

**Comment by shubham4564** [comment]
We can also target TTL room, which is great for presentations and workshops and well equiped too.

**Comment by shubham4564** [comment]
Update on Venue:
1. Available for 16th Sept, need to write a letter to HOD of DoCSE for the room, he'll then forward memo to Mechanocal depart HOD, will submit the letter tomorrow.
2. There might be wifi available by 16th sept in TTL but we should be prepared with our routers as backup.

**Comment by sigdelsanjog** [comment]
Closing this Issue as Resolved as @shubham4564 is taking ownership of Finalizing Venue.
