### ISSUE TITLE
Event Registration at softwarefreedomday.org

### ISSUE THREAD

**Issue by sigdelsanjog** [Kathmandu-University-Computer-Club/SFD2017#2]
Event Registration at softwarefreedomday.org with event details.
TBD: Event Structure

**Comment by sigdelsanjog** [comment]
http://wiki.softwarefreedomday.org/2017/Nepal/Kavre?highlight=%28%5CbCategoryCity2017%5Cb%29
Completed the Registration Task . Please review the description and make necessary changes if I've missed any.

**Comment by shubham4564** [comment]
Below is the Event Registration Page, Our event is not registered yet, I think only team has been registered.

https://www.softwarefreedomday.org/cgi-bin/register.py

**Comment by sigdelsanjog** [comment]
@shubham4564 I registered event for FOSS-KAVRE, You can lead the team and Register KUOSC with your email id.
