### ISSUE TITLE
[3] Budget Estimation

### ISSUE THREAD

**Issue by sigdelsanjog** [Kathmandu-University-Computer-Club/SFD2017#7]
- Budget Estimation
- Fund Will be provided for this event by KUCC. A 2 page proposal describing the event structure and budget estimation should be submitted to KUCC adressing to the President. KUOSC Co-ordinator or any Volunteer can write this to the President of KUCC

Major budget allocation will be only for Tea and Bevarage which won't cross an estimation of NRs. 1000/-

**Comment by irigpratit** [comment]
On Monday I'll fix about money from KUCC

**Comment by shubham4564** [comment]
Talked with KUCC president and general secretary for budget, they are positive for NRs 1000 as mentioned above but need to give exact amount we will he needing for our basic need..

**Comment by sigdelsanjog** [comment]
@shubham4564 : Above estimated 1000 was my estimation for around 20-30 Members. Incase we will have 50 participants that won't be enough. Like you guys say there can be 50 participants we need to refreshments ready for that day.

**Comment by shubham4564** [comment]
Cookies => 4 Packets => Rs 400
Tea => 50 cups => Rs 15 x 50 => Rs 750
Flex => 1 Flex => Rs 750
Chartpapers (for slogan writing) => 10 teams => 1 paper per team => Rs 5 x 10 => Rs 50

Total => Rs 1950 ~ Rs 2000

is there anything left?

**Comment by sigdelsanjog** [comment]
This looks good.
@shubham4564 : I've kept the POSTERS of SFD2015 at Narayan Dai's Office. Shubham/ @irigpratit  can get it from him.
